name: NomadServer
id: nomad-server
version: 0.1.0
category: Bitcoin
port: 3829
path: /

compose:
  services:
    nomad-server:
      image: zenderady/nomad-server:latest
      restart: unless-stopped

      ports:
        - "3829:3829"

      volumes:
        - data:/data

      networks:
        - umbrel_main_network

      environment:
        UMBREL_APP_DATA_DIR: /data
        UMBREL_APP_ID: nomad-server
        ELECTRS_ADDR: electrs:50001

  volumes:
    data:

  networks:
    umbrel_main_network:
      external: true